---
title: "Untitled"
author: "Jens Åström"
date: "10/14/2018"
output: pdf_document
---

```{r setup, include=FALSE}

require(tidyverse)
require(SurveyPower)
```

```{r}
data("predWeights1km")
```



```{r, eval = F}

system.time(predOcc500Det1 <- weightedDetection(occWeights = predWeights1km,
                              visWeights = predWeights1km,
                              noOccur = 500,
                              noLocations = seq(50, 300, by = 50),
                              noVisits = 1,
                              detectProb = 1,
                              nIter = 999))

save(predOcc500Det1, file = "predOcc500Det1.Rdata")


```
```{r}
load("predOcc500Det1.Rdata")
```


```{r, eval = F}

system.time(predOcc500Det0.8 <- weightedDetection(occWeights = predWeights1km,
                              visWeights = predWeights1km,
                              noOccur = 500,
                              noLocations = seq(50, 300, by = 50),
                              noVisits = 1,
                              detectProb = 0.8,
                              nIter = 999))

save(predOcc500Det0.8, file = "predOcc500Det0.8.Rdata")


```
```{r}

load(file = "predOcc500Det0.8.Rdata")
plot(threshold = 0.8, xlab = "Antall lokaliteter", ylab = "Observasjonssannsynlighet", predOcc500Det0.8)
predOcc500Det0.8
```


```{r, eval = F}

system.time(predOcc500Det0.2 <- weightedDetection(occWeights = predWeights1km,
                              visWeights = predWeights1km,
                              noOccur = 500,
                              noLocations = seq(200, 1000, by = 200),
                              noVisits = 1,
                              detectProb = 0.2,
                              nIter = 999))


save(predOcc500Det0.2, file = "predOcc500Det0.2.Rdata")


```
```{r}
load(file = "predOcc500Det0.2.Rdata")
plot(threshold = 0.8, xlab = "Antall lokaliteter", ylab = "Observasjonssannsynlighet", predOcc500Det0.2)
predOcc500Det0.2
```




```{r, eval = F}

system.time(predOcc200Det0.8 <- weightedDetection(occWeights = predWeights1km,
                              visWeights = predWeights1km,
                              noOccur = 200,
                              noLocations = seq(50, 600, by = 50),
                              noVisits = 1,
                              detectProb = 0.8,
                              nIter = 999))

save(predOcc200Det0.8, file = "predOcc200Det0.8.Rdata")


```
```{r}

load(file = "predOcc200Det0.8.Rdata")
plot(threshold = 0.8, xlab = "Antall lokaliteter", ylab = "Observasjonssannsynlighet", predOcc200Det0.8)
predOcc200Det0.8
```


```{r, eval = F}

system.time(predOcc100Det0.8 <- weightedDetection(occWeights = predWeights1km,
                              visWeights = predWeights1km,
                              noOccur = 100,
                              noLocations = seq(50, 600, by = 50),
                              noVisits = 1,
                              detectProb = 0.8,
                              nIter = 999))

save(predOcc100Det0.8, file = "predOcc100Det0.8.Rdata")


```
```{r}

load(file = "predOcc100Det0.8.Rdata")
plot(threshold = 0.8, xlab = "Antall lokaliteter", ylab = "Observasjonssannsynlighet", predOcc100Det0.8)
predOcc100Det0.8
```




```{r, eval = F}

system.time(predOcc200Det0.2 <- weightedDetection(occWeights = predWeights1km,
                              visWeights = predWeights1km,
                              noOccur = 200,
                              noLocations = seq(200, 1000, by = 200),
                              noVisits = 1,
                              detectProb = 0.2,
                              nIter = 999))

save(predOcc200Det0.2, file = "predOcc200Det0.2.Rdata")


```
```{r}

load(file = "predOcc200Det0.2.Rdata")
plot(threshold = 0.8, xlab = "Antall lokaliteter", ylab = "Observasjonssannsynlighet", predOcc200Det0.2)
predOcc200Det0.2
```


```{r, eval = F}

system.time(predOcc100Det0.2 <- weightedDetection(occWeights = predWeights1km,
                              visWeights = predWeights1km,
                              noOccur = 100,
                              noLocations = seq(200, 1000, by = 200),
                              noVisits = 1,
                              detectProb = 0.2,
                              nIter = 999))

save(predOcc100Det0.2, file = "predOcc100Det0.2.Rdata")


```
```{r}

load(file = "predOcc100Det0.2.Rdata")
plot(threshold = 0.8, xlab = "Antall lokaliteter", ylab = "Observasjonssannsynlighet", predOcc100Det0.2)
predOcc100Det0.2
```


```{r, eval = F}

system.time(predOcc500Det0.5 <- weightedDetection(occWeights = predWeights1km,
                              visWeights = predWeights1km,
                              noOccur = 500,
                              noLocations = seq(200, 1000, by = 200),
                              noVisits = 1,
                              detectProb = 0.5,
                              nIter = 999))

save(predOcc500Det0.5, file = "predOcc500Det0.5.Rdata")


```
```{r}

load(file = "predOcc500Det0.5.Rdata")
plot(threshold = 0.8, xlab = "Antall lokaliteter", ylab = "Observasjonssannsynlighet",
     predOcc500Det0.5)
predOcc500Det0.5
```


```{r, eval = F}

system.time(predOcc200Det0.5 <- weightedDetection(occWeights = predWeights1km,
                              visWeights = predWeights1km,
                              noOccur = 200,
                              noLocations = seq(200, 1000, by = 200),
                              noVisits = 1,
                              detectProb = 0.5,
                              nIter = 999))

save(predOcc200Det0.5, file = "predOcc200Det0.5.Rdata")


```
```{r}

load(file = "predOcc200Det0.5.Rdata")
plot(threshold = 0.8, xlab = "Antall lokaliteter", ylab = "Observasjonssannsynlighet", predOcc200Det0.5)
predOcc200Det0.5
```

```{r, eval = F}

system.time(predOcc100Det0.5 <- weightedDetection(occWeights = predWeights1km,
                              visWeights = predWeights1km,
                              noOccur = 100,
                              noLocations = seq(200, 1000, by = 200),
                              noVisits = 1,
                              detectProb = 0.5,
                              nIter = 999))

save(predOcc100Det0.5, file = "predOcc100Det0.5.Rdata")


```
```{r}

load(file = "predOcc100Det0.5.Rdata")
plot(threshold = 0.8, xlab = "Antall lokaliteter", ylab = "Observasjonssannsynlighet", predOcc100Det0.5)
predOcc100Det0.5
```




Test visiting only 1/16 of the plot.

```{r, eval = F}

system.time(predOcc500Det0.05 <- weightedDetection(occWeights = predWeights1km,
                              visWeights = predWeights1km,
                              noOccur = 500,
                              noLocations = seq(200, 1000, by = 200),
                              noVisits = 1,
                              detectProb = 0.8/16,
                              nIter = 999))

save(predOcc500Det0.05, file = "predOcc500Det0.05.Rdata")


```
```{r}

load(file = "predOcc500Det0.05.Rdata")
plot(threshold = 0.8, xlab = "Antall lokaliteter", ylab = "Observasjonssannsynlighet", predOcc500Det0.05)
predOcc500Det0.05
```



Test visit 4 times instead but lower no locations for same sample effort.
```{r, eval = F}

system.time(predOcc500Det0.05Vis4 <- weightedDetection(occWeights = predWeights1km,
                              visWeights = predWeights1km,
                              noOccur = 500,
                              noLocations = seq(200, 1000, by = 200),
                              noVisits = 4,
                              detectProb = 0.8/16,
                              nIter = 999))

save(predOcc500Det0.05Vis4, file = "predOcc500Det0.05Vis4.Rdata")


```
```{r}

load(file = "predOcc500Det0.05Vis4.Rdata")
plot(threshold = 0.8, xlab = "Antall lokaliteter", ylab = "Observasjonssannsynlighet", predOcc500Det0.05Vis4)
predOcc500Det0.05Vis4
```



Test visit 10 times instead but lower no locations for same sample effort.
```{r, eval = F}

system.time(predOcc500Det0.05Vis10 <- weightedDetection(occWeights = predWeights1km,
                              visWeights = predWeights1km,
                              noOccur = 500,
                              noLocations = seq(200, 1000, by = 200),
                              noVisits = 10,
                              detectProb = 0.8/16,
                              nIter = 999))

save(predOcc500Det0.05Vis10, file = "predOcc500Det0.05Vis10.Rdata")


```
```{r}

load(file = "predOcc500Det0.05Vis10.Rdata")
plot(threshold = 0.8, xlab = "Antall lokaliteter", ylab = "Observasjonssannsynlighet", predOcc500Det0.05Vis10)
predOcc500Det0.05Vis10
```


----------


Even lower detectibility. 0.4/16

```{r, eval = F}

system.time(predOcc500Det0.025Vis4 <- weightedDetection(occWeights = predWeights1km,
                              visWeights = predWeights1km,
                              noOccur = 500,
                              noLocations = seq(200, 1000, by = 200),
                              noVisits = 4,
                              detectProb = 0.4/16,
                              nIter = 999))

save(predOcc500Det0.025Vis4, file = "predOcc500Det0.025Vis4.Rdata")


```
```{r}

load(file = "predOcc500Det0.025Vis4.Rdata")
plot(threshold = 0.8, xlab = "Antall lokaliteter", ylab = "Observasjonssannsynlighet", predOcc500Det0.025Vis4)
predOcc500Det0.025Vis4
```



Test visit 10 times instead but lower no locations for same sample effort.
```{r, eval = F}

system.time(predOcc500Det0.025Vis10 <- weightedDetection(occWeights = predWeights1km,
                              visWeights = predWeights1km,
                              noOccur = 500,
                              noLocations = seq(200, 1000, by = 200),
                              noVisits = 10,
                              detectProb = 0.4/16,
                              nIter = 999))

save(predOcc500Det0.025Vis10, file = "predOcc500Det0.025Vis10.Rdata")


```
```{r}

load(file = "predOcc500Det0.025Vis10.Rdata")
plot(threshold = 0.8, xlab = "Antall lokaliteter", ylab = "Observasjonssannsynlighet", predOcc500Det0.025Vis10)
predOcc500Det0.025Vis10
```

Again 100 occurrences but with lower detectability

```{r, eval = F}

system.time(predOcc100Det0.05Vis1 <- weightedDetection(occWeights = predWeights1km,
                              visWeights = predWeights1km,
                              noOccur = 100,
                              noLocations = seq(200, 1000, by = 200),
                              noVisits = 1,
                              detectProb = 0.8/16,
                              nIter = 999))

save(predOcc100Det0.05Vis1, file = "predOcc100Det0.05Vis1.Rdata")


```
```{r}

load(file = "predOcc100Det0.05Vis1.Rdata")
plot(threshold = 0.8, xlab = "Antall lokaliteter", ylab = "Observasjonssannsynlighet", predOcc100Det0.05Vis1)
predOcc100Det0.05Vis1
```


```{r, eval = F}

system.time(predOcc100Det0.05Vis4 <- weightedDetection(occWeights = predWeights1km,
                              visWeights = predWeights1km,
                              noOccur = 100,
                              noLocations = seq(200, 1000, by = 200),
                              noVisits = 4,
                              detectProb = 0.8/16,
                              nIter = 999))

save(predOcc100Det0.05Vis4, file = "predOcc100Det0.05Vis4.Rdata")


```
```{r}

load(file = "predOcc100Det0.05Vis4.Rdata")
plot(threshold = 0.8, xlab = "Antall lokaliteter", ylab = "Observasjonssannsynlighet", predOcc100Det0.05Vis4)
predOcc100Det0.05Vis4
```


```{r, eval = F}

system.time(predOcc100Det0.05Vis10 <- weightedDetection(occWeights = predWeights1km,
                              visWeights = predWeights1km,
                              noOccur = 100,
                              noLocations = seq(200, 1000, by = 200),
                              noVisits = 10,
                              detectProb = 0.8/16,
                              nIter = 999))

save(predOcc100Det0.05Vis10, file = "predOcc100Det0.05Vis10.Rdata")


```
```{r}

load(file = "predOcc100Det0.05Vis10.Rdata")
plot(threshold = 0.8, xlab = "Antall lokaliteter", ylab = "Observasjonssannsynlighet", predOcc100Det0.05Vis10)
predOcc100Det0.05Vis10
``` 


