
```{r}
require(SurveyPower)
```


```{r}


poisTrend <- createOccPois(map10km,
                                       intercept = 22,
                                       sigmaFylke = 0.4,
                                       sigmaKommune = 0.1,
                                       sigmaGrid = 0.05,
                                       nYears = 10,
                                       interceptTrend = 0.95,
                                       sdInterceptTrend = 0,
                                       sigmaFylkeTrend = 0,
                                       sigmaKommuneTrend = 0,
                                       sortGrid = F,
                                       sortFylke = F,
                                       sortKommune = F,
                                       artypeEff = c("Bebygd" = 1,
                                                     "Samferdsel" = 1,
                                                     "Fulldyrka jord" = 1.1,
                                                     "Overflatedyrka jord" = 1,
                                                     "Innmarksbeite" = 1,
                                                     "Skog" = 1,
                                                     "Åpen fastmark" = 1,
                                                     "Myr" = 0.9,
                                                     "Isbre" = 1,
                                                     "Ferskvann" = 1,
                                                     "Hav" = 1,
                                                     "Ikke kartlagt" = 1),
                                       artypeTrend = c("Bebygd" = 1,
                                                       "Samferdsel" = 1,
                                                       "Fulldyrka jord" = 1,
                                                       "Overflatedyrka jord" = 1.05,
                                                       "Innmarksbeite" = 1,
                                                       "Skog" = 1,
                                                       "Åpen fastmark" = 1,
                                                       "Myr" = 1,
                                                       "Isbre" = 1,
                                                       "Ferskvann" = 1,
                                                       "Hav" = 1,
                                                       "Ikke kartlagt" = 1)
)

```


```{r}
poisTrend$map %>% 
  select(ARTYPE, lambda, year) %>% 
    ggplot(.) + 
  geom_line(aes(x = year, y = lambda, color = ARTYPE), 
            stat = "summary", fun.y = "mean", lwd =2)

```

```{r}

draw <- samplePois(poisTrend, 
                   yearlyCapacity = 100)

draw %>% 
  select(ARTYPE, nCount, year) %>% 
    ggplot(.) + 
  geom_line(aes(x = year, y = nCount, color = ARTYPE), 
            stat = "summary", fun.y = "mean", lwd =2)

```

```{r}
trend <- seq(22, 10, by = -.15)

pois <- rpois(10, trend)

plot(pois, type = "l", col = 1, lwd = 1.5)

for(i in 2:10){
  pois <- rpois(10, trend)
  lines(pois, type = "l", col = i, add = T, lwd = 1.5)
}

```




```{r}

poisPar <- estimatePars(map = poisTrend, 
                        sampleFun = "samplePois", 
                        samplePars = c("yearlyCapacity" = 400),
                        model = "poissonFull",
                        nIter = 10
                        )

warnings()

poisPar

```
```{r}
poisParComp <- compareEstPar(poisPar)

poisParComp
```


```{r}
tt <- weightedDetection(noOccur = 2,
  noLocations = 1:10,
 detectProb =  0.5,
 noVisits = 10)
 
plot(tt) +
  ggtitle("2 visits at each location") 


```


```{r}
hm <- weightedDetection(noOccur = 2,
  noLocations = 1:10,
 detectProb =  0.5,
 noVisits = 10,
 occWeights = data.frame(site = 10:1, weights = c(0.05, 0.05,
  0.05, 0.05, 0.1, 0.1, 0.1, 0.1, 0.2, 0.2)))
 
plot(hm) +
  ggtitle("2 visits at each location") 


```


```{r}
require(RPostgreSQL)
require(DBI)
require(rpostgis)

con <- dbConnect(RPostgreSQL::PostgreSQL(), host = "gisdata-db.nina.no", dbname = "gisdata", user = "postgjest", password = "gjestpost")

pred <- pgGetRast(con, name = c("hotspot_ias", "bigPred1km"), rast = "rast", bands = 1, boundary = NULL)

pred

```


```{r}
occWeights <- data.frame("site" = 1:length(pred),
                         "weights" = pred@data@values
                         )
occWeights$weights[is.na(occWeights$weights)] <- 0

predDetect <- weightedDetection(occWeights = occWeights,
                                obsWeights = occWeights,
                                noOccur = 500,
                                noLocations = 100,
                                noVisits = 5
                                )

plot(predDetect)

```


```{r}

test <- function(){
              visited <- sample(1:4057, 50, replace = F)
              occupied <- sample(1:4057, 50, replace = F)
              
              any(visited %in% occupied)
}


sum(replicate(1000, test())/1000)

```


